#!/usr/bin/env python

import os
import wget
import shutil


MODEL_CACHE = "weights"
if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


wget.download(
    "https://github.com/isl-org/MiDaS/releases/download/v3_1/dpt_beit_large_512.pt",
    out=f"{MODEL_CACHE}/dpt_beit_large_512.pt",
)
wget.download(
    "https://github.com/isl-org/MiDaS/releases/download/v3_1/dpt_swin2_large_384.pt",
    out=f"{MODEL_CACHE}/dpt_swin2_large_384.pt",
)
wget.download(
    "https://github.com/isl-org/MiDaS/releases/download/v3_1/dpt_swin2_tiny_256.pt",
    out=f"{MODEL_CACHE}/dpt_swin2_tiny_256.pt",
)
wget.download(
    "https://github.com/isl-org/MiDaS/releases/download/v3_1/dpt_levit_224.pt",
    out=f"{MODEL_CACHE}/dpt_levit_224.pt",
)
